### ISSUE TITLE
# sign cannot be written inside LaTeX

### ISSUE THREAD

**Issue by naslundx** [Mattecentrum/Mattemotor#4]

**Comment by ericmattecentrum** [comment]
Hej! Nu har jag semester. Är åter på kontoret den 3 augisti. 

Läser mejl lite sporadiskt under de här veckorna. Det går bra att skicka ett mess till 073-060 33 00.

Trevlig sommar!

/Eric Persson

**Comment by torandersson** [comment]
fungerar \(#F00\) latex
